name = "Ludwig"
uuid = "71a25704-ed10-46ea-9c76-1c441b891988"
authors = ["Davis Thuillier <dsthuillier@gmail.com>"]
version = "0.2.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DataStructures = "0.18.20"
ForwardDiff = "0.10.36"
Interpolations = "0.15.1"
IterativeSolvers = "0.9.4"
StaticArrays = "^1.9.4"
LinearAlgebra = ">= 1.1.0"
julia = "^1.8.2"
